server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  # RabbitMQ相关配置
  rabbitmq:
    host: 47.95.226.96
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          # 外部仓库地址
          uri: https://github.com/812467457/springcloud-config.git
          # 搜索目录
          search-paths: springcloud-config
      # 分支
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka


# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'